import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  SUPERADMIN_USERNAME: z.string().default("admin"),
  SUPERADMIN_PASSWORD_HASH: z.string().min(20),
  JWT_SECRET: z.string().min(32),
  JWT_EXPIRY: z.coerce.number().default(86400),
  TOTP_ISSUER: z.string().default("VPS Panel"),
  TOTP_ENCRYPTION_KEY: z.string().min(32),
  PANEL_PORT: z.coerce.number().default(4000),
  PANEL_LOGIN_PORT: z.string().default("8453"),
  CPANEL_LOGIN_PORT: z.string().default("3138"),
  DEPLOYMENT_PORT_START: z.coerce.number().int().min(1024).max(65535).default(10000),
  DEPLOYMENT_PORT_END: z.coerce.number().int().min(1024).max(65535).default(19999),
  DEPLOYMENT_RESERVED_PORTS: z.string().default("22,25,53,80,110,143,443,465,587,993,995,3000,3010,3138,4000,5000,5432,6379,8453"),
  DEPLOYMENT_LOG_ROOT: z.string().default("/var/log/vps-panel/deployments"),
  DEPLOY_WORKER_CONCURRENCY: z.coerce.number().int().min(1).max(10).default(1),
  DEPLOY_SYSTEM_RESERVE_MB: z.coerce.number().int().min(512).default(4096),
  DEPLOY_MIN_APP_RESERVE_MB: z.coerce.number().int().min(512).default(8192),
  DEPLOY_APP_RESERVE_MULTIPLIER: z.coerce.number().min(1).default(2),
  DEPLOY_MIN_MEMORY_MB: z.coerce.number().int().min(512).default(3072),
  DEPLOY_MAX_MEMORY_MB: z.coerce.number().int().min(1024).default(12288),
  DEPLOY_FREE_CPU_CORES: z.coerce.number().int().min(0).default(2),
  DEPLOY_WEB_RUNTIME_OPTIMIZATION_ENABLED: z.coerce.boolean().default(true),
  PANEL_UPDATE_WEBHOOK_SECRET: z.string().optional(),
  PANEL_UPDATE_REPO_FULL_NAME: z.string().optional(),
  PANEL_UPDATE_BRANCH: z.string().default("main"),
  PANEL_UPDATE_WORKDIR: z.string().default(process.cwd().replace(/\/api$/, "")),
  PANEL_UPDATE_SCRIPT: z.string().optional(),
  PANEL_UPDATE_STATUS_FILE: z.string().default("/var/log/vps-panel/self-update-status.json"),
  PANEL_UPDATE_LOG_FILE: z.string().default("/var/log/vps-panel/self-update.log"),
  PANEL_UPDATE_PID_FILE: z.string().default("/tmp/vps-panel-self-update.pid"),
  PANEL_UPDATE_API_SERVICE: z.string().default("vps-panel-api"),
  PANEL_UPDATE_STALE_AFTER_SECONDS: z.coerce.number().default(1200),
  PANEL_UPDATE_POLL_ENABLED: z.coerce.boolean().default(true),
  PANEL_UPDATE_POLL_REMOTE: z.string().default("origin"),
  PANEL_UPDATE_POLL_INTERVAL_MS: z.coerce.number().default(60_000),
  FRONTEND_URL: z.string().url().default("http://localhost:3000"),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1).default("redis://localhost:6379"),
  SYSAGENT_URL: z.string().url().default("http://127.0.0.1:5000"),
  VPS_IP: z.string().default("127.0.0.1"),
  REQUIRE_DOMAIN_NAMESERVER_MATCH: z.coerce.boolean().default(true),
  ALLOW_PENDING_DOMAIN_NAMESERVER_MISMATCH: z.coerce.boolean().default(false),
  ALLOW_VANITY_NAMESERVER_GLUE_FALLBACK: z.coerce.boolean().default(true),
  ALLOW_PENDING_VANITY_NAMESERVER_DOMAINS: z.coerce.boolean().default(false),
  DOMAIN_NAMESERVER_RESOLVERS: z.string().default("1.1.1.1,8.8.8.8,9.9.9.9"),
  DOMAIN_NAMESERVER_DOH_URLS: z.string().default("https://cloudflare-dns.com/dns-query,https://dns.google/resolve,https://dns.quad9.net/dns-query"),
  ACCOUNT_DOMAIN_AUTO_SSL_ENABLED: z.coerce.boolean().default(true),
  ACCOUNT_DOMAIN_AUTO_SSL_RETRY_DELAY_MS: z.coerce.number().int().min(60_000).default(600_000),
  ACCOUNT_DOMAIN_AUTO_SSL_ATTEMPTS: z.coerce.number().int().min(1).max(1000).default(432),
  FILE_MANAGER_ROOT: z.string().default("/var/www"),
  FILE_MANAGER_UPLOAD_LIMIT_BYTES: z.coerce.number().int().nonnegative().default(0),
  FILE_MANAGER_UPLOAD_CHUNK_BYTES: z.coerce.number().int().positive().default(16 * 1024 * 1024),
  GUARDIAN_TRUSTED_CIDRS: z.string().default(""),
  GUARDIAN_AUTO_DEPLOY_POLL_ENABLED: z.coerce.boolean().default(true),
  GUARDIAN_AUTO_DEPLOY_POLL_INTERVAL_MS: z.coerce.number().default(60_000),
  ALLOW_LIVE_WHM_MIGRATION: z.coerce.boolean().default(false)
});

export const env = envSchema.parse(process.env);
